name:                wai-middleware-verbs
version:             0.4.0
github:              "athanclark/wai-middleware-verbs"
license:             BSD3
author:              "Athan Clark"
maintainer:          "athan.clark@localcooking.com"
copyright:           "2018 Athan Clark"
category:            Web
synopsis:            Route Wai middlewares based on HTTP verbs

ghc-options: -Wall

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://git.localcooking.com/tooling/wai-middleware-verbs#readme>

dependencies:
- base >= 4.8 && < 5
- bytestring
- exceptions
- hashable
- http-types
- monad-logger
- mmorph
- mtl
- resourcet
- transformers
- transformers-base
- unordered-containers
- wai >= 3.2.1
- wai-transformers >= 0.1.0

library:
  source-dirs: src
